name: Send Email on JSON Update

on:
  push:
    paths:
      - '**.json'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mxschmitt/action-tmate@v2
      - name: send-email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: JSON file updated in the repository
          body: |
            The following commit has updated a JSON file in the repository:
            Commit message: ${{ github.event.head_commit.message }}
            Commit author: ${{ github.event.head_commit.author.name }}
            Commit URL: ${{ github.event.head_commit.url }}
          to: vengadesh@vthink.co.in